src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>D_B_Phone__c</fullName>
        <label>D&amp;B - Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Direct_Mail_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Direct Mail Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Wearers__c</fullName>
        <label>Number of Wearers</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Top_25__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Top 25</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <referenceTo>Note__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Note__c.object
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RetrieveAccountServiceTest.cls
/**
* This class tests the functionality of RetrieveAccountService class
*/
@isTest
public class RetrieveAccountServiceTest{
    
    static Account account;
    
    /**
    * Create test data
    */
    private static void createTestData(){
        account = new Account();
        account.Name = 'Test Account';
        account.Type = 'Customer - Direct';
        account.D_B_Phone__c =  '1234567890';
        account.Number_of_Wearers__c = 12;
        account.Top_25__c = true;
        account.Direct_Mail_Opt_Out__c = false;
        insert account;
    }
    
    /**
    * This method tests modified retrieveAccount
    */
    public static TestMethod void testModifiedRetrieveAccount(){
        // create test data
        createTestData();
        Contact contact = TestClassSetup.createContact('Test LastName', account.Id);
        TestClassSetup.createEvent(Date.today(), UserInfo.getUserId(), account.Id, contact.Id);
        TestClassSetup.createTask(Date.today(), Date.today(), UserInfo.getUserId(), account.Id);
        Opportunity opportunity = TestClassSetup.createOpportunity('Test Opportunity - 001', account.Id);
        TestClassSetup.createQuote('Test Quote - 001', opportunity.Id);
        Note__c note = TestClassSetup.createNote('Test Note', 'Test text', account.Id);
        ContentVersion content = [SELECT ContentDocumentId FROM ContentVersion where Id = :TestClassSetup.createContent().Id];
        
        Attachment__c attachment = TestClassSetup.createAttachment(note.Id, content.ContentDocumentId);
        
        RestRequest request = new RestRequest();
        request.requestURI = TestClassSetup.RESTAPI_BASEURL + 
            TestClassSetup.RESTAPI_GLOBAL_RETRIEVE_ACCOUNT_URL;
        request.params.put('accountId',account.Id);
        RestContext.request = request;
        
        // start testing
        Test.startTest();
        RetrieveAccountService.AccountWrapper result = RetrieveAccountService.retrieveAccount();
        Test.stopTest();
        
        // validating the result
        system.assertEquals(account.Id , result.id);
        system.assertEquals('true', result.top25);
        system.assertEquals('false', result.directMailOptOut);
    }
    
    /**
    * This method tests retrieveAccount
    */
    public static TestMethod void testRetrieveAccount(){
        createTestData();
        RestRequest request = new RestRequest();
        request.params.put('accountId',account.Id);
        RestContext.request = request;
        Test.startTest();
        RetrieveAccountService.AccountWrapper result = RetrieveAccountService.retrieveAccount();
        Test.stopTest();
        system.assertEquals(account.Id , result.id);
        system.assertEquals('true', result.top25);
        system.assertEquals('false', result.directMailOptOut);
    }
    
    /**
    * This method tests retrieveAccount when account Id is not passed
    */
    public static TestMethod void testRetrieveAccountNotPassedAccId(){
        RestRequest request = new RestRequest();
        RestContext.request = request;
        Test.startTest();
        RetrieveAccountService.AccountWrapper result = RetrieveAccountService.retrieveAccount();
        Test.stopTest();
        system.assertEquals(false, result.isSuccess);
    }
    
    /**
    * This method tests retrieveAccount when account Id is invalid
    */
    public static TestMethod void testRetrieveAccountInvalidAccId(){
        RestRequest request = new RestRequest();
        request.params.put('accountId','test');
        RestContext.request = request;
        Test.startTest();
        RetrieveAccountService.AccountWrapper result = RetrieveAccountService.retrieveAccount();
        Test.stopTest();
        system.assertEquals(false, result.isSuccess);
    }
}