src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Competitor_1__c</fullName>
        <label>Incumbent</label>
        <picklist>
            <picklistValues>
                <fullName>Alsco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriPride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aramark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Linen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cintas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prudential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unifirst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competitor_2__c</fullName>
        <label>Incumbent 2</label>
        <picklist>
            <picklistValues>
                <fullName>Alsco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriPride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aramark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Linen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cintas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prudential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unifirst</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Cash_Value__c</fullName>
        <description>Seller Pre-Opportunity estimated cash value of a prospect</description>
        <label>Estimated Cash Value</label>
        <picklist>
            <picklistValues>
                <fullName>&lt; 50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50 - 100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100 - 250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250 - 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500 - 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 1000</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Incumbent_DP__c</fullName>
        <label>Incumbent DP</label>
        <picklist>
            <picklistValues>
                <fullName>DP 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DP 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DP 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DP 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mega_Segment__c</fullName>
        <label>Mega Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Segment 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segment 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segment 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Type_1__c</fullName>
        <label>Program Type 1</label>
        <picklist>
            <picklistValues>
                <fullName>Market Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program - Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program - Direct Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unclassified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N.O.G.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Stage__c</fullName>
        <label>Sales Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Approach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Present/Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Prep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect - Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect - Not Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect - Previously Quit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mark for Deletion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Made at Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Made Elsewhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natl Acct - Do Not Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Contracted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer - Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>SVP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GlobalMetadataService.cls
/**
* This rest service is used to retrive options for picklists
*/
@RestResource(urlMapping='/Global/Metadata')
global class GlobalMetadataService {
    /**
    * This method gets called when get http method is performed
    */
    @HttpGet
    global static void retriveMetadata() {
        // Form Map of Objects and related Fields
        Map<String, Map<String, Schema.SObjectField>> mapObjectField =
            new Map<String, Map<String, Schema.SObjectField>>{
                SObjectType.Account.Name => SObjectType.Account.fields.getMap(),
                SObjectType.Contact.Name => SObjectType.Contact.fields.getMap(),
                SObjectType.Opportunity.Name => SObjectType.Opportunity.fields.getMap(),
                SObjectType.Lead.Name => SObjectType.Lead.fields.getMap()
            };
        // Form Map of Objects and related Picklist Fields
        Map<String, Set<String>> mapObjectFieldSet =
            new Map<String, Set<String>>{
                SObjectType.Account.Name => new Set<String> {
                    '' + Account.Status__c, 
                    '' + Account.Sales_Stage__c, 
                    '' + Account.Estimated_Cash_Value__c, 
                    '' + Account.Program_Type_1__c, 
                    '' + Account.Competitor_1__c, 
                    '' + Account.Competitor_2__c, 
                    '' + Account.Incumbent_DP__c, 
                    '' + Account.Mega_Segment__c
                },
                SObjectType.Contact.Name => new Set<String> {
                    '' + Contact.Role__c 
                },
                SObjectType.Opportunity.Name => new Set<String> {
                    '' + Opportunity.Type, 
                    '' + Opportunity.Primary_Customer_Promise__c, 
                    '' + Opportunity.Close_Reason__c, 
                    '' + Opportunity.Who_Won__c, 
                    '' + Opportunity.Competitors__c
                },
                SObjectType.Lead.Name => new Set<String> {
                    '' + Lead.Salutation, 
                    '' + Lead.Status, 
                    '' + Lead.Industry
                }
            };
        
        // Prepare Map of Picklist field and related Options
        Map<String, String[]> mapPicklistOptions = new Map<String, String[]>();
        
        for(String objectName : mapObjectField.keySet()) {
            for(String fieldName : mapObjectFieldSet.get(objectName)) {
                Schema.DescribeFieldResult describeFieldResult = mapObjectField.get(objectName).get(fieldName).getDescribe();
                if('PICKLIST'.equalsIgnoreCase(String.valueOf(describeFieldResult.getType()))) {
                    String field = objectName + '.' + describeFieldResult.getName();
                    for(Schema.PicklistEntry picklistEntry : describeFieldResult.getPicklistValues()) {
                        if(mapPicklistOptions.containsKey(field)) {
                            mapPicklistOptions.get(field).add(picklistEntry.getLabel());
                        } else {
                            mapPicklistOptions.put(field, new String [] {picklistEntry.getLabel()});
                        }
                    }
                }
            }
        }
        
        // Prepare the list of Fields for sorting
        List<String> lstFields = new List<String> (mapPicklistOptions.keySet());
        lstFields.sort();
        
        // Create a JSONGenerator object
        JSONGenerator gen = JSON.createGenerator(true);
        // Write data to the JSON string.
        gen.writeStartObject();
        
        for(String fieldName : lstFields) {
            gen.writeObjectField(fieldName, mapPicklistOptions.get(fieldName));
        }
        gen.writeEndObject();
        // Add the generated JSON to response
        if(Test.isRunningTest()) {
            RestContext.response = new RestResponse();
        }
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(gen.getAsString());
    }
}