src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Alias__c</fullName>
        <label>Account Alias</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CED_1__c</fullName>
        <label>CED 1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CED_2__c</fullName>
        <label>CED 2</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Competitor_1__c</fullName>
        <label>Incumbent</label>
        <picklist>
            <picklistValues>
                <fullName>Alsco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriPride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aramark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Linen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cintas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prudential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unifirst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competitor_2__c</fullName>
        <label>Incumbent 2</label>
        <picklist>
            <picklistValues>
                <fullName>Alsco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AmeriPride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aramark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canadian Linen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cintas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prudential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unifirst</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Cash_Value__c</fullName>
        <description>Seller Pre-Opportunity estimated cash value of a prospect</description>
        <label>Estimated Cash Value</label>
        <picklist>
            <picklistValues>
                <fullName>&lt; 50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50 - 100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100 - 250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250 - 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500 - 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt; 1000</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GK_Employees_Here__c</fullName>
        <label>GK Employees Here</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incumbent_DP__c</fullName>
        <label>Incumbent DP</label>
        <picklist>
            <picklistValues>
                <fullName>DP 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DP 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DP 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DP 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mega_Segment__c</fullName>
        <label>Mega Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Segment 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segment 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Segment 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Wearers__c</fullName>
        <label>Number of Wearers</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Incumbent__c</fullName>
        <label>Other Incumbent</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Type_1__c</fullName>
        <label>Program Type 1</label>
        <picklist>
            <picklistValues>
                <fullName>Market Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program - Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program - Direct Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unclassified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N.O.G.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateAccountService.cls
/*
* This rest service is used Create Account
*/

@RestResource(urlMapping='/Account/Create')
global class CreateAccountService {

    /**
    * This method gets called when POST http method is performed
    */
    @HttpPost
    global static ResponseWrapper createAccount(AccountWrapper accountWrapper) {
        ResponseWrapper response = new ResponseWrapper();
        try {
            // Create the account from the passed object
            Account objAccount = new Account(
                Name = accountWrapper.name,
                Account_Alias__c = accountWrapper.accountAlias,
                Phone = accountWrapper.phone,
                ShippingStreet = accountWrapper.shippingStreet,
                ShippingCity = accountWrapper.shippingCity,
                ShippingState = accountWrapper.shippingState,
                ShippingCountry = accountWrapper.shippingCountry,
                ShippingPostalCode = accountWrapper.shippingPostalCode,
                Estimated_Cash_Value__c = accountWrapper.estimatedCashValue,
                Program_Type_1__c = accountWrapper.programType1,
                Competitor_1__c = accountWrapper.competitor1,
                Other_Incumbent__c = accountWrapper.otherIncumbent,
                CED_1__c = ServiceUtils.getDate(accountWrapper.ced1),
                Competitor_2__c = accountWrapper.competitor2,
                CED_2__c = ServiceUtils.getDate(accountWrapper.ced2),
                Incumbent_DP__c = accountWrapper.incumbentDP,
                GK_Employees_Here__c = accountWrapper.gKEmployeesHere,
                Number_of_Wearers__c = accountWrapper.numberOfWearers,
                Mega_Segment__c = accountWrapper.megaSegment
            );
            insert objAccount;
            
            // Return the success response
            response.Id = objAccount.Id;
            response.isSuccess = true;
            response.message = 'Created successfully';
        } catch (Exception objEx) {
            // Catch the exception if any
            response.isSuccess = false;
            response.message = objEx.getMessage();
        }
        return response;
    }
    
    /**
    * This wrapper stores Account data which is accepted as input parameter
    */
    global class AccountWrapper {
        public String name;
	    public String accountAlias;
	    public String phone;
	    public String shippingStreet;
	    public String shippingCity;
	    public String shippingState;
	    public String shippingCountry;
	    public String shippingPostalCode;
	    public String estimatedCashValue;
	    public String programType1;
	    public String competitor1;
	    public String otherIncumbent;
	    public String ced1;
	    public String competitor2;
	    public String ced2;
	    public String incumbentDP;
	    public Integer gKEmployeesHere;
	    public Integer numberOfWearers;
	    public String megaSegment;
    }
    
    /**
    * This wrapper stores response data
    */
    global class ResponseWrapper {
        public String message;
        public String Id;
        public Boolean isSuccess;
    }
}