src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerPriority__c</fullName>
        <label>Customer Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>French-Canadian</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NumberofLocations__c</fullName>
        <label>Number of Locations</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Rental</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>DP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLAExpirationDate__c</fullName>
        <label>SLA Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLASerialNumber__c</fullName>
        <label>SLA Serial Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Departments</relationshipLabel>
        <relationshipName>Departments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Department_Embellishment__c.object
<CustomObject>
    <fields>
        <fullName>Department_Line_Item__c</fullName>
        <label>Department Line Item</label>
        <referenceTo>Department_Line_Item__c</referenceTo>
        <relationshipLabel>Department Embellishments</relationshipLabel>
        <relationshipName>Department_Embellishments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Embellishment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Embellishment</label>
        <referenceTo>Embellishment__c</referenceTo>
        <relationshipLabel>Department Embellishments</relationshipLabel>
        <relationshipName>Department_Embellishments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Department Embellishment</label>
    <nameField>
        <label>Department Embellishment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Embellishments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Department_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Department Line Items</relationshipLabel>
        <relationshipName>Department_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Product</label>
        <referenceTo>Opportunity_Product__c</referenceTo>
        <relationshipLabel>Department Line Items</relationshipLabel>
        <relationshipName>Department_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Department Line Item</label>
    <nameField>
        <label>Department Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Embellishment__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Embellishment</label>
    <nameField>
        <label>Embellishment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Embellishments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Embellishment__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Embellishment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Embellishment</label>
        <referenceTo>Embellishment__c</referenceTo>
        <relationshipLabel>Invoice Embellishments</relationshipLabel>
        <relationshipName>Invoice_Embellishments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Item__c</fullName>
        <label>Invoice Line Item</label>
        <referenceTo>Invoice_Line_Item__c</referenceTo>
        <relationshipLabel>Invoice Embellishments</relationshipLabel>
        <relationshipName>Invoice_Embellishments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Embellishment</label>
    <nameField>
        <label>Invoice Embellishment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Embellishments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Invoice</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unique Product</label>
        <referenceTo>Unique_Product__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wearer__c</fullName>
        <label>Wearer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wearer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Product__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Products</relationshipLabel>
        <relationshipName>Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Product</label>
    <nameField>
        <label>Opportunity Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Embellishment__c.object
<CustomObject>
    <fields>
        <fullName>Embellishment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Embellishment</label>
        <referenceTo>Embellishment__c</referenceTo>
        <relationshipLabel>Quote Embellishments</relationshipLabel>
        <relationshipName>Quote_Embellishments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote Embellishment</label>
    <nameField>
        <label>Quote Embellishment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Embellishments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Delivery_Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Agreements</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Agreements</relationshipLabel>
        <relationshipName>Service_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Agreement</label>
    <nameField>
        <label>Service Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unique_Product__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Unique Products</relationshipLabel>
        <relationshipName>Unique_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unique Product</label>
    <nameField>
        <label>Unique Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unique Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessQueryUtil.cls
/*
* This class forms all dynamic SOQLs without where clauses.
* Any field, added later & which needs to be queried, can be added in appropriate dynamic SOQL string.
*/
public with sharing class ProcessQueryUtil {
    
    public static String getSkinnyAccountFieldsQuery() {
        String retVal = 'Select Id,Name,'+
                      'Current_Opportunity__r.Id,'+
                      'Current_Opportunity__r.Sizing_Complete__c '+
                 'From Account ';
    
        return retVal;     
    }//end getSkinnyAccountFieldsQuery
    
    public static String getSkinnyQueryForDepartmentLineItem() {
        return 'Select Id,Name,'+
                       'Department__c,'+
                       'External_ID__c,'+
                       '(Select Id,Name,'+
                                'Description__c,'+
                                'External_ID__c'+
                         ' From Department_Embellishments__r)'+
                ' From Department_Line_Item__c ';
    }//end getSkinnyQueryForDepartmentLineItem
    
    public static String getSkinnyQueryForInvoiceLineItem() {
        return 'Select Id,Name,'+
                        'Invoice__c,'+
                        'External_ID__c,'+
                        'Wearer__c,'+
                        '(Select Id,Name,'+
                                'Description__c,'+
                                'External_ID__c'+
                         ' From Invoice_Embellishments__r)'+
               ' From Invoice_Line_Item__c';
    }//end getSkinnyQueryForInvoiceLineItem
    
    public static String getSkinnyQueryForUniqueProduct() {
        return 'Select Id,Name From Unique_Product__c ';
    }//end getSkinnyQueryForUniqueProduct
    
    public static String getSkinnyQueryForQuoteEmbellishment() {
        String retVal = 'Select Id,Name,'+
                               'Embellishment__c,'+
                               'Embellishment__r.Name,'+
                               'Embellishment__r.Location__c'+
                        ' From Quote_Embellishment__c';
        return retVal;
    }//end getSkinnyQueryForQuoteEmbellishment
    
    public static String getSkinnyQueryForOpportunityProducts() {
        String retVal = 'Select Id,Name,'+
                             'Product__r.Id,'+
                             'Product__r.Name,'+
                             'Product__r.Family,'+
                             'Product__r.Description,'+
                             'Product__r.ProductCode,'+
                             'Product__r.IsActive'+
                        ' From Opportunity_Product__c ';
        return retVal;
    }//end getSkinnyQueryForOpportunityProducts
    
    public static String getSkinnyQueryForFitSession() {
        Map<String,RecordType> rtMap = ServiceUtils.getRecordTypeMap();
        String retVal = 'Select Id,Name,'+
                                'parentID,'+
                                '(Select Id,Name,'+
                                        'FirstName,'+
                                        'LastName,'+
                                        'accountId,'+
                                        'Department,'+
                                        'External_Id__c,'+
                                        'Locker_Number__c,'+
                                        'Locker_Bank__c,'+
                                        'Notes__c,'+
                                        'Gender__c'+
                                 ' From Contacts '+
                                 ' Where RecordTypeID = '+ '\'' + rtMap.get(System.Label.WEARER_RECORD_TYPE).Id + '\'' +'),'+
                                '(Select Id,Name,'+
                                        'Address__c,'+
                                        'External_ID__c,'+
                                        'Delivery_Location__c'+
                                 ' From Departments__r),'+
                               '(Select Id,Name,'+
                                       'Opportunity__c'+
                                ' From Service_Agreements__r),'+
                               '(Select ID,Name From Opportunities),'+
                               '(Select Id,Name, '+
                                        'AccountNumber,'+
                                        'Active__c,'+
                                        'AnnualRevenue,'+
                                        'BillingCity,'+
                                        'BillingCountry,'+
                                        'BillingPostalCode,'+
                                        'BillingState,'+
                                        'BillingStreet,'+
                                        'Current_Opportunity__c,'+
                                        'CustomerPriority__c,'+
                                        'Description,'+
                                        'External_ID__c,'+
                                        'Fax,'+
                                        'Industry,'+
                                        'Language__c,'+
                                        'NumberofLocations__c,'+
                                        'Ownership,'+
                                        'ParentId,'+
                                        'Phone,'+
                                        'Product_Type__c,'+
                                        'Rating,'+
                                        'ShippingCity,'+
                                        'ShippingCountry,'+
                                        'ShippingPostalCode,'+
                                        'ShippingState,'+
                                        'ShippingStreet,'+
                                        'Sic,'+
                                        'Site,'+
                                        'SLAExpirationDate__c,'+
                                        'SLASerialNumber__c,'+
                                        'SLA__c,'+
                                        'TickerSymbol,'+
                                        'Type,'+
                                        'UpsellOpportunity__c,'+
                                        'Website '+
                               ' From ChildAccounts  Where RecordTypeID =\''+ rtMap.get(System.Label.INVOICE_RECORD_TYPE).Id +'\')'+                 
                         'From Account';
        return retVal;
    }//end getSkinnyQueryForFitSession.
}//end class.