src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Invoice</fullName>
        <active>true</active>
        <label>Invoice</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Wearer</fullName>
        <active>true</active>
        <label>Wearer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Department_Embellishment__c.object
<CustomObject>
    <fields>
        <fullName>Department_Line_Item__c</fullName>
        <label>Department Line Item</label>
        <referenceTo>Department_Line_Item__c</referenceTo>
        <relationshipLabel>Department Embellishments</relationshipLabel>
        <relationshipName>Department_Embellishments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Embellishment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Embellishment</label>
        <referenceTo>Embellishment__c</referenceTo>
        <relationshipLabel>Department Embellishments</relationshipLabel>
        <relationshipName>Department_Embellishments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Department Embellishment</label>
    <nameField>
        <label>Department Embellishment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Embellishments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Department_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Department Line Items</relationshipLabel>
        <relationshipName>Department_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Department Line Item</label>
    <nameField>
        <label>Department Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Embellishment__c.object
<CustomObject>
    <label>Embellishment</label>
    <nameField>
        <label>Embellishment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Embellishments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Embellishment__c.object
<CustomObject>
    <fields>
        <fullName>Embellishment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Embellishment</label>
        <referenceTo>Embellishment__c</referenceTo>
        <relationshipLabel>Invoice Embellishments</relationshipLabel>
        <relationshipName>Invoice_Embellishments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Item__c</fullName>
        <label>Invoice Line Item</label>
        <referenceTo>Invoice_Line_Item__c</referenceTo>
        <relationshipLabel>Invoice Embellishments</relationshipLabel>
        <relationshipName>Invoice_Embellishments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Embellishment</label>
    <nameField>
        <label>Invoice Embellishment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Embellishments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Invoice</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unique Product</label>
        <referenceTo>Unique_Product__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wearer__c</fullName>
        <label>Wearer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wearer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <label>Invoice Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Unique_Product__c.object
<CustomObject>
    <label>Unique Product</label>
    <nameField>
        <label>Unique Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unique Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FitSessionWrapper.cls
/*
* This is wrapper class for FitSession Infromation Webservice response.
*/
global with sharing class FitSessionWrapper extends Response{
    
    public DataWrapper data;
    
    /*
    * Inner Wrapper class for complete data.
    */
    public class DataWrapper { 
        //list of Departments, Department Line Items, Department Embellishments.
        public List<DepartmentWrapper> departments;
        
        //List of Contacts, Invoice Line Items, Invoice Embellishments.
        public List<ContactWrapper> contacts;
        
        //List of Opportunity Products through Service agreement relationship.
        public List<Product2> opportunityProducts;
        
        //List of Unique Products through Product Relationship.
        public List<Unique_Product__c> uniqueProducts;
        
        //List of Embellishments related to Quote Embellishments.
        public List<Embellishment__c> embellishments;
        
        //list of accounts where parentId = provided account Id.
        public List<Account> invoices;
    }//end DataWrapper class.
    
    /*
    * constructor
    */
    public FitSessionWrapper(){
        data = new DataWrapper();
        
        data.departments = new List<DepartmentWrapper>();
        data.contacts = new List<ContactWrapper>();
        data.opportunityProducts = new List<Product2>();
        data.uniqueProducts = new List<Unique_Product__c>();
        data.embellishments = new List<Embellishment__c>();
        data.invoices = new List<Account>();
    }
    
    /*
    * Department Section.
    */
    public class DepartmentWrapper {
        String name;
        String id;
        String externalId;
        String address;
        
        List<DepartmentLineItemWrapper> departmentLineItems;
        
        public DepartmentWrapper(Department__c department,
                                 List<DepartmentLineItemWrapper> departmentLineItems) {
            this.name = department.Name;
            this.id   = department.Id;
            this.externalId = department.External_Id__c;
            this.address = department.Address__c;                            
            this.departmentLineItems = departmentLineItems;
        }
    }//end DepartmentWrapper class.
    
    /*
    * Department Line Item & Embellishment Wrapper.
    */
    public class DepartmentLineItemWrapper {
        String id;
        String name;
        String opportunityId;
        String externalId;
        
        List<Department_Embellishment__c> departmentEmbellishments;
    
        public DepartmentLineItemWrapper(Department_Line_Item__c departmentLineItem,
                                         List<Department_Embellishment__c> departmentEmbellishments) {
            this.id = departmentLineItem.Id;
            this.name = departmentLineItem.Name;
            this.opportunityId = departmentLineItem.Id;
            this.externalId = departmentLineItem.External_Id__c;
            this.departmentEmbellishments = departmentEmbellishments;                            
        }
    }//end DepartmentLineItemWrapper class
    
    /* 
    * Contact Section.
    */
    
    public class ContactWrapper {
        public String name;
        public String accountId;
        public String firstName;
        public Id id;
        public String department;
        public String lastName;
        List<InvoiceLineItemWrapper> invoiceLineItems;
        
        public ContactWrapper(Contact contact,
                              List<InvoiceLineItemWrapper> invoiceLineItems) {
            this.name = contact.Name;
            this.accountId = contact.AccountId;
            this.firstName = contact.firstName;
            this.lastName = contact.lastName;
            this.department = contact.department;
            this.invoiceLineItems = invoiceLineItems;
        }
    }//end ContactWrapper class.
    
    /*
    * Invoice Line Item & Embellishments wrapper.
    */ 
    public class InvoiceLineItemWrapper {
        public String name;
        public String wearer;
        public String externalID;
        public Id id;
        public String invoice;
        List<Invoice_Embellishment__c> invoiceEmbellishments;   
        
        public InvoiceLineItemWrapper(Invoice_Line_Item__c invoiceLineItem,
                                      List<Invoice_Embellishment__c> invoiceEmbellishments) {
            this.name  = invoiceLineItem.Name;
            this.id    = invoiceLineItem.Id;
            this.wearer= invoiceLineItem.Wearer__c;
            this.externalId = invoiceLineItem.External_Id__c;
            this.invoice = invoiceLineItem.Invoice__C;                        
            this.invoiceEmbellishments = invoiceEmbellishments;                            
        }                                      
    }//end InvoiceLineItemWrapper class.
}//end class